### ISSUE TITLE
[homer] Update bjw-s dependency version

### ISSUE THREAD

**Issue by Saintetix** [djjudas21/charts#113]
### Describe the bug a clear and concise description of what the bug is.

Homer's chart use an older version of `bjw-s helm-charts`.

```
dependencies:
  - name: common
    repository: http://bjw-s.github.io/helm-charts/
    version: 0.2.0
```

Currently, the version is at [3.5.1](https://github.com/bjw-s/helm-charts/tree/main/charts/other/app-template).
Maybe you can set the dependency version to the new one ?

### What's your helm version?

v2.17.0

### What's your kubectl version?

v1.28.15

### Which chart?

homer

### What's the chart version?

8.2.0

### Enter the command that you execute and failing/misfunctioning.

`helmfile sync -l app=homer`
