### ISSUE TITLE
[smtp-relay] monitoring enabled causes CrashLoopBackOff

### ISSUE THREAD

**Issue by leleobhz** [djjudas21/charts#146]
### Describe the bug a clear and concise description of what the bug is.

Hello!

Enabling monitoring causes the following log in `chatwork/kumina-postfix-exporter:edge` pod:

```
2025/05/15 17:06:22 Reading log events from /var/log/maillog
2025/05/15 17:06:22 Failed to create PostfixExporter: open /var/log/maillog: no such file or directory
```

What is the proper way to fix it?

Thanks!

### What's your helm version?

version.BuildInfo{Version:"v3.17.3", GitCommit:"e4da49785aa6e6ee2b86efd5dd9e43400318262b", GitTreeState:"", GoVersion:"go1.24.2"}

### What's your kubectl version?

Client Version: v1.32.4 Kustomize Version: v5.5.0 Server Version: v1.32.4+k0s

### Which chart?

smtp-relay

### What's the chart version?

latest

### Enter the changed values of values.yaml?

```yaml
metrics:
  enabled: false
  prometheusRules:
    enabled: true
  serviceMonitor:
    enabled: true
smtp:
  host: "<REDACTED>"
  username: "<REDACTED>"
  password: "<REDACTED>"
  hostname: "<REDACTED>"
  mynetworks:
    - "10.244.0.0/16"
    - "192.168.42.0/24"
    - "fd00::/108"
  tls_security_level: "encrypt"
  tls_wrappermode: "yes"

service:
  type: ClusterIP
  loadBalancerIP: "192.168.50.1"
  port: 25

```

### Enter the command that you execute and failing/misfunctioning.

```
helm upgrade --kube-context=brgvhomekubearmorial --install --history-max=1 --create-namespace --namespace=smtp-relay --repo https://djjudas21.github.io/charts/ --values smtp-relay.values.yaml smtp-relay smtp-relay
```
